[
  {
    "url": "https://api.github.com/repos/quarnster/SublimeClang/issues/comments/13192493",
    "html_url": "https://github.com/quarnster/SublimeClang/issues/192#issuecomment-13192493",
    "issue_url": "https://api.github.com/repos/quarnster/SublimeClang/issues/192",
    "id": 13192493,
    "user": {
      "login": "rchl",
      "id": 153197,
      "avatar_url": "https://secure.gravatar.com/avatar/6e76f284c370ff9510a4898e028b0962?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
      "gravatar_id": "6e76f284c370ff9510a4898e028b0962",
      "url": "https://api.github.com/users/rchl",
      "html_url": "https://github.com/rchl",
      "followers_url": "https://api.github.com/users/rchl/followers",
      "following_url": "https://api.github.com/users/rchl/following",
      "gists_url": "https://api.github.com/users/rchl/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rchl/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rchl/subscriptions",
      "organizations_url": "https://api.github.com/users/rchl/orgs",
      "repos_url": "https://api.github.com/users/rchl/repos",
      "events_url": "https://api.github.com/users/rchl/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rchl/received_events",
      "type": "User"
    },
    "created_at": "2013-02-06T17:01:14Z",
    "updated_at": "2013-02-06T17:01:22Z",
    "body": "I wanted to try it and got:\r\n\r\nTraceback (most recent call last):\r\n  File \"C:\\programy\\Sublime3\\Data\\Packages\\SublimeClang\\sublimeclang.py\", line 36, in <module>\r\n    import Queue\r\nImportError: No module named 'Queue'\r\n\r\nwhich seems weird to me as it's inside 'try' block so should rather run code in 'except' block...\r\n\r\nI was trying 23ee17178bae9d18340b3033fb5a159e4958ee14 on Windows.\r\n\r\nBTW. Is clang DLL no longer shipped with the plugin? Where am I supposed to get it from?"
  },
  {
    "url": "https://api.github.com/repos/quarnster/SublimeClang/issues/comments/13194687",
    "html_url": "https://github.com/quarnster/SublimeClang/issues/192#issuecomment-13194687",
    "issue_url": "https://api.github.com/repos/quarnster/SublimeClang/issues/192",
    "id": 13194687,
    "user": {
      "login": "quarnster",
      "id": 1230389,
      "avatar_url": "https://secure.gravatar.com/avatar/10a89302c6736c988ce06d8a41c923c0?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
      "gravatar_id": "10a89302c6736c988ce06d8a41c923c0",
      "url": "https://api.github.com/users/quarnster",
      "html_url": "https://github.com/quarnster",
      "followers_url": "https://api.github.com/users/quarnster/followers",
      "following_url": "https://api.github.com/users/quarnster/following",
      "gists_url": "https://api.github.com/users/quarnster/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/quarnster/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/quarnster/subscriptions",
      "organizations_url": "https://api.github.com/users/quarnster/orgs",
      "repos_url": "https://api.github.com/users/quarnster/repos",
      "events_url": "https://api.github.com/users/quarnster/events{/privacy}",
      "received_events_url": "https://api.github.com/users/quarnster/received_events",
      "type": "User"
    },
    "created_at": "2013-02-06T17:39:17Z",
    "updated_at": "2013-02-06T17:39:17Z",
    "body": "Dll's aren't in the repo, you can pull them from a [binary package](https://github.com/quarnster/SublimeClang/downloads)."
  },
  {
    "url": "https://api.github.com/repos/quarnster/SublimeClang/issues/comments/13195699",
    "html_url": "https://github.com/quarnster/SublimeClang/issues/192#issuecomment-13195699",
    "issue_url": "https://api.github.com/repos/quarnster/SublimeClang/issues/192",
    "id": 13195699,
    "user": {
      "login": "rchl",
      "id": 153197,
      "avatar_url": "https://secure.gravatar.com/avatar/6e76f284c370ff9510a4898e028b0962?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
      "gravatar_id": "6e76f284c370ff9510a4898e028b0962",
      "url": "https://api.github.com/users/rchl",
      "html_url": "https://github.com/rchl",
      "followers_url": "https://api.github.com/users/rchl/followers",
      "following_url": "https://api.github.com/users/rchl/following",
      "gists_url": "https://api.github.com/users/rchl/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rchl/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rchl/subscriptions",
      "organizations_url": "https://api.github.com/users/rchl/orgs",
      "repos_url": "https://api.github.com/users/rchl/repos",
      "events_url": "https://api.github.com/users/rchl/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rchl/received_events",
      "type": "User"
    },
    "created_at": "2013-02-06T17:59:18Z",
    "updated_at": "2013-02-06T18:00:06Z",
    "body": "If I workaround problem with importing (just leave the 'except' block), I get:\r\n\r\n```\r\nTraceback (most recent call last):\r\n  File \"C:\\programy\\Sublime3\\sublime_plugin.py\", line 70, in reload_plugin\r\n    m = importlib.import_module(modulename)\r\n  File \"X/importlib/__init__.py\", line 88, in import_module\r\n  File \"<frozen importlib._bootstrap>\", line 1577, in _gcd_import\r\n  File \"<frozen importlib._bootstrap>\", line 1558, in _find_and_load\r\n  File \"<frozen importlib._bootstrap>\", line 1525, in _find_and_load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 586, in _check_name_wrapper\r\n  File \"<frozen importlib._bootstrap>\", line 1023, in load_module\r\n  File \"<frozen importlib._bootstrap>\", line 1004, in load_module\r\n  File \"<frozen importlib._bootstrap>\", line 562, in module_for_loader_wrapper\r\n  File \"<frozen importlib._bootstrap>\", line 869, in _load_module\r\n  File \"<frozen importlib._bootstrap>\", line 313, in _call_with_frames_removed\r\n  File \"C:\\programy\\Sublime3\\Data\\Packages\\SublimeClang\\sublimeclang.py\", line 36, in <module>\r\n    from .internals.clang import cindex\r\n  File \"C:\\programy\\Sublime3\\Data\\Packages\\SublimeClang\\internals\\clang\\cindex.py\", line 118, in <module>\r\n    lib = get_cindex_library()\r\n  File \"C:\\programy\\Sublime3\\Data\\Packages\\SublimeClang\\internals\\clang\\cindex.py\", line 86, in get_cindex_library\r\n    return cdll.LoadLibrary(\"libclang_x64.dll\")\r\n  File \"X/ctypes/__init__.py\", line 431, in LoadLibrary\r\n  File \"X/ctypes/__init__.py\", line 353, in __init__\r\nOSError: [WinError 126] The specified module could not be found\r\n```\r\n\r\nWith libclang_x64.dll in the plugin's directory. I had to move it to the SublimeText's directory to make plugin work."
  },
  {
    "url": "https://api.github.com/repos/quarnster/SublimeClang/issues/comments/14005810",
    "html_url": "https://github.com/quarnster/SublimeClang/issues/192#issuecomment-14005810",
    "issue_url": "https://api.github.com/repos/quarnster/SublimeClang/issues/192",
    "id": 14005810,
    "user": {
      "login": "jjgod",
      "id": 1017,
      "avatar_url": "https://secure.gravatar.com/avatar/2dd3e7469ade9ddedc6781133a39525e?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
      "gravatar_id": "2dd3e7469ade9ddedc6781133a39525e",
      "url": "https://api.github.com/users/jjgod",
      "html_url": "https://github.com/jjgod",
      "followers_url": "https://api.github.com/users/jjgod/followers",
      "following_url": "https://api.github.com/users/jjgod/following",
      "gists_url": "https://api.github.com/users/jjgod/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jjgod/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jjgod/subscriptions",
      "organizations_url": "https://api.github.com/users/jjgod/orgs",
      "repos_url": "https://api.github.com/users/jjgod/repos",
      "events_url": "https://api.github.com/users/jjgod/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jjgod/received_events",
      "type": "User"
    },
    "created_at": "2013-02-24T09:27:42Z",
    "updated_at": "2013-02-24T09:28:00Z",
    "body": "On ST3 startup, I got the following errors in console, btw:\r\n\r\n    reloading plugin SublimeClang.common\r\n    Traceback (most recent call last):\r\n      File \"/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py\", line 71, in reload_plugin\r\n        m = importlib.import_module(modulename)\r\n      File \"X/importlib/__init__.py\", line 88, in import_module\r\n      File \"<frozen importlib._bootstrap>\", line 1577, in _gcd_import\r\n      File \"<frozen importlib._bootstrap>\", line 1558, in _find_and_load\r\n      File \"<frozen importlib._bootstrap>\", line 1522, in _find_and_load_unlocked\r\n    ImportError: No module named 'SublimeClang.common'\r\n\r\n    reloading plugin SublimeClang.sublimeclang\r\n    Traceback (most recent call last):\r\n      File \"/Users/jjgod/Library/Application Support/Sublime Text 3/Packages/SublimeClang/sublimeclang.py\", line 36, in <module>\r\n        import Queue\r\n    ImportError: No module named 'Queue'\r\n\r\n    reloading plugin SublimeClang.translationunitcache\r\n    Traceback (most recent call last):\r\n      File \"/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py\", line 71, in reload_plugin\r\n        m = importlib.import_module(modulename)\r\n      File \"X/importlib/__init__.py\", line 88, in import_module\r\n      File \"<frozen importlib._bootstrap>\", line 1577, in _gcd_import\r\n      File \"<frozen importlib._bootstrap>\", line 1558, in _find_and_load\r\n      File \"<frozen importlib._bootstrap>\", line 1522, in _find_and_load_unlocked\r\n    ImportError: No module named 'SublimeClang.translationunitcache'"
  },
  {
    "url": "https://api.github.com/repos/quarnster/SublimeClang/issues/comments/14005971",
    "html_url": "https://github.com/quarnster/SublimeClang/issues/192#issuecomment-14005971",
    "issue_url": "https://api.github.com/repos/quarnster/SublimeClang/issues/192",
    "id": 14005971,
    "user": {
      "login": "quarnster",
      "id": 1230389,
      "avatar_url": "https://secure.gravatar.com/avatar/10a89302c6736c988ce06d8a41c923c0?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
      "gravatar_id": "10a89302c6736c988ce06d8a41c923c0",
      "url": "https://api.github.com/users/quarnster",
      "html_url": "https://github.com/quarnster",
      "followers_url": "https://api.github.com/users/quarnster/followers",
      "following_url": "https://api.github.com/users/quarnster/following",
      "gists_url": "https://api.github.com/users/quarnster/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/quarnster/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/quarnster/subscriptions",
      "organizations_url": "https://api.github.com/users/quarnster/orgs",
      "repos_url": "https://api.github.com/users/quarnster/repos",
      "events_url": "https://api.github.com/users/quarnster/events{/privacy}",
      "received_events_url": "https://api.github.com/users/quarnster/received_events",
      "type": "User"
    },
    "created_at": "2013-02-24T09:45:09Z",
    "updated_at": "2013-02-24T09:45:09Z",
    "body": "Did you use the git version? The binary package isn't ready for ST3."
  },
  {
    "url": "https://api.github.com/repos/quarnster/SublimeClang/issues/comments/14006195",
    "html_url": "https://github.com/quarnster/SublimeClang/issues/192#issuecomment-14006195",
    "issue_url": "https://api.github.com/repos/quarnster/SublimeClang/issues/192",
    "id": 14006195,
    "user": {
      "login": "jjgod",
      "id": 1017,
      "avatar_url": "https://secure.gravatar.com/avatar/2dd3e7469ade9ddedc6781133a39525e?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
      "gravatar_id": "2dd3e7469ade9ddedc6781133a39525e",
      "url": "https://api.github.com/users/jjgod",
      "html_url": "https://github.com/jjgod",
      "followers_url": "https://api.github.com/users/jjgod/followers",
      "following_url": "https://api.github.com/users/jjgod/following",
      "gists_url": "https://api.github.com/users/jjgod/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jjgod/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jjgod/subscriptions",
      "organizations_url": "https://api.github.com/users/jjgod/orgs",
      "repos_url": "https://api.github.com/users/jjgod/repos",
      "events_url": "https://api.github.com/users/jjgod/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jjgod/received_events",
      "type": "User"
    },
    "created_at": "2013-02-24T10:07:27Z",
    "updated_at": "2013-02-24T10:07:27Z",
    "body": "Yes, it is the git version, somehow I have to mess with install_name_tool myself to get libclang.dylib loaded, but these output is after I got rid of the loading problem and SublimeClang is working properly, but I wonder if there is a way to prevent such messages."
  }
]
